name: 'checkov'

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  checkov:
    name: 'checkov'
    runs-on: ubuntu-latest
    environment: production

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2

    - name: Checkov AWS
      # You may pin to the exact commit or the version.
      # uses: bridgecrewio/checkov-action@00cc657f4d415593e5c8897bc87f490497ccb5f9
      uses: bridgecrewio/checkov-action@v12.876.0
      with:
        # directory with infrastructure code to scan
        directory: terraform/ # optional, default is .
        # Run scan only on a specific check identifier (comma separated)
        # check: CKV_AWS_1 # optional
        # Run scan on all checks but a specific check identifier (comma separated)
        # skip_check: # optional
        # display only failed checks
        quiet: true # optional should be true
        # do not return an error code if there are failed checks
        soft_fail: true # optional
        # run only on a specific infrastructure
        framework: terraform # optional
        # comma separated list of external (custom) checks directories
        # external_checks_dirs: # optional
        # comma separated list of external (custom) checks repositories
        # external_checks_repos: # optional
        # The format of the output. cli, json, junitxml, github_failed_only
        output_format: github_failed_only # optional
        # download external terraform modules from public git repositories and terraform registry:true, false
        download_external_modules: true # optional
        # log level
        # log_level: # optional, default is WARNING

    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7.7
    - name: Run checkov analysis
      run: |
        python --version
        python -m pip install --upgrade pip setuptools
        python -m pip install --upgrade 'checkov==2.0.418'
        checkov --version
        checkov --framework terraform -s -d terraform/ -o sarif > checkov.sarif
    - name: Expose report
      uses: actions/upload-artifact@v2
      with:
        name: SARIF results
        path: checkov.sarif
    # Uploads results.sarif to GitHub repository using the upload-sarif action
    - uses: github/codeql-action/upload-sarif@v1
      with:
        # Path to SARIF file relative to the root of the repository
        sarif_file: checkov.sarif