# This workflow integrates Scan with GitHub's code scanning feature
# Scan is a free open-source security tool for modern DevOps teams from ShiftLeft
# Visit https://slscan.io/en/latest/integrations/code-scan for help
name: 'scan (ShiftLeftSecurity)'

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  scan:
    name: 'scan (ShiftLeftSecurity)'
    # Scan runs on ubuntu, mac and windows
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Perform Scan
      uses: ShiftLeftSecurity/scan-action@master
      env:
        WORKSPACE: ""
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SCAN_AUTO_BUILD: false
      with:
        output: shiftleft-reports

    - name: Upload report
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: shiftleft-reports
